### ISSUE TITLE
JMComic-Crawler-Python的api今天出现无法使用的情况 导致插件初始化失败的处理办法

### ISSUE THREAD

**Issue by exneverbur** [exneverbur/ShowMeJM#22]
尝试使用以下指令更新
```
pip install jmcomic -i https://pypi.org/project -U
``` 
若还是不行 可能是安装到了其他python版本上, 使用此指令安装到指定python版本
```
py -<你的版本> -m pip install jmcomic –i https://pypi.org/project –U
```
比如我的python是3.10.10 则使用
```
py –3.10 -m pip install jmcomic –i https://pypi.org/project –U
```
若还是不能访问 使用下面的方法
1. impl改为使用html![Image](https://github.com/user-attachments/assets/ac6235ab-2c5b-4319-9620-4deaeb554637)
2.main.py中关闭随机本子功能(因为此功能依赖api)

![Image](https://github.com/user-attachments/assets/358ca481-1aa8-40ed-b154-624d88fbda5d)

**Comment by exneverbur** [comment]
或修改config.yml文件, 改为如下配置，指定使用这些下载域名。 用此方法可以不用关闭随机本子功能
```
client:
  impl: api
  domain:
    api:
      - www.cdnmhwscc.vip
      - www.cdnblackmyth.club
      - www.cdnmhws.cc
      - www.cdnuc.vip
  ```

**Comment by wuxianyu9908** [comment]
加了域名好了

**Comment by exneverbur** [comment]
解决了 我这边是pip对应python版本和系统配置的不一致导致依赖装在其他py上了
使用此指令安装到指定python版本
```
py -<你的版本> -m pip install jmcomic –i https://pypi.org/project –U
```
比如我的python是3.10.10 则使用
```
py –3.10 -m pip install jmcomic –i https://pypi.org/project –U
```

**Comment by exneverbur** [comment]
若还是不行拿只能在config里手动指定域名
``` yml
client:
  impl: api
  domain:
    api:
      - www.cdnmhwscc.vip
      - www.cdnblackmyth.club
      - www.cdnmhws.cc
      - www.cdnuc.vip
```
